#应用名称
spring:
  application:
    name: blog
  profiles:
    active: "@activatedProperties@"
    # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

knife4j:
  # 开启接口文档增强 []
  enable: true
  # 生产环境打开, 禁用文档接口
  #production: true
  # 文档登录验证
#  basic:
#    username: test
#    password: 123456
#    enable: true

#mybatis配置
mybatis-plus:
  executor-type: reuse
  configuration:
    cache-enabled: false
    aggressive-lazy-loading: true
    jdbc-type-for-null: 'null'
  type-aliases-package: com.xiahl.blog.domain
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
  check-config-location: true

pagehelper:
  supportMethodsArguments: true
  reasonable: false
  params: count=countSql


# mybatis配置
#mybatis:
#  type-aliases-package: com.xiahl.blog.domain
#  mapper-locations: classpath*:/mapper/*.xml
#  configuration:
#    # 驼峰映射默认关闭
#    map-underscore-to-camel-case: true
#    #Mybatis的sql日志打印, 测试的时候开启
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


