#应用名称
spring:
  application:
    name: blog
  profiles:
    active: "@activatedProperties@"
    # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.61.242:3306/blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

knife4j:
  # 开启接口文档增强 []
  enable: true
  # 生产环境打开, 禁用文档接口
  #production: true
  # 文档登录验证
#  basic:
#    username: test
#    password: 123456
#    enable: true

#mybatis配置
mybatis-plus:
  executor-type: reuse
  configuration:
    cache-enabled: false
    aggressive-lazy-loading: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xiahl.blog.domain
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
  check-config-location: true

pagehelper:
  supportMethodsArguments: true
  reasonable: false
  params: count=countSql

  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 124.222.61.242 # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password: 123456  # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8    # 连接池中的最大空闲连接 默认 8
        min-idle: 0    # 连接池中的最小空闲连接 默认 0
# mybatis配置
#mybatis:
#  type-aliases-package: com.xiahl.blog.domain
#  mapper-locations: classpath*:/mapper/*.xml
#  configuration:
#    # 驼峰映射默认关闭
#    map-underscore-to-camel-case: true
#    #Mybatis的sql日志打印, 测试的时候开启
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


